# Generated by Django 5.1.3 on 2024-11-24 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_joined_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format international : '+123456789' avec 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
